logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: trace

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

server:
  port: 8080
